[supervisord]
nodaemon=true


[program:celery_worker]
command=celery -A banking_api worker --pool=solo --loglevel=info
directory=C:\banking_api_project
autostart=true
autorestart=true
stdout_logfile=logs/celery_worker.log
stderr_logfile=logs/celery_worker_error.log


[program:celery_beat]
command=celery -A banking_api beat --loglevel=info
directory=C:\banking_api_project
autostart=true
autorestart=true
stdout_logfile=logs/celery_beat.log
stderr_logfile=logs/celery_beat_error.log