# Generated by Django 6.0.6 on 2026-07-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current Account')], max_length=20),
        ),
    ]
