# Generated by Django 6.0.6 on 2026-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('INTEREST', 'Monthly Interest'), ('EMI_PAYMENT', 'EMI Payment'), ('LOAN_FORECLOSURE', 'Loan Foreclosure')], max_length=20),
        ),
    ]
