# Generated by Django 6.0.6 on 2026-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_emi_penalty_amount_alter_emi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
    ]
