# Generated by Django 6.0.6 on 2026-07-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='transaction_limit',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
    ]
